CREATE TABLE IF NOT EXISTS authorities
(
  username VARCHAR(512) NOT NULL,
  authority VARCHAR(512) NOT NULL,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) NOT NULL,
  organization_id INT NOT NULL
);
CREATE TABLE IF NOT EXISTS contacts
(
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) NOT NULL,
  vcard LONGVARCHAR,
  hash_code VARCHAR(512),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_offline TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS contacts_users
(
  contact_id INT NOT NULL,
  user_id INT NOT NULL,
  user_is_owner BOOLEAN DEFAULT false NOT NULL,
  notes VARCHAR(512),
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) NOT NULL,
  organization_id INT,
  connection_updated_offline TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  connection_added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  version INT DEFAULT 0 NOT NULL
);
CREATE TABLE IF NOT EXISTS organizations
(
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) NOT NULL,
  name VARCHAR(512),
  url VARCHAR(512),
  hash_code VARCHAR(512),
  template_image_path VARCHAR(512),
  logo_image_path VARCHAR(512),
  template_layout VARCHAR(512),
  template_as_svg VARCHAR(16384),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS organizations_users
(
  organization_id INT NOT NULL,
  user_id INT NOT NULL,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) NOT NULL,
  search_public_key VARCHAR(512),
  search_public_key_for_co_workers VARCHAR(512)
);
CREATE TABLE IF NOT EXISTS schema_version
(
  version_rank INT NOT NULL,
  installed_rank INT NOT NULL,
  version VARCHAR(50) PRIMARY KEY NOT NULL,
  description VARCHAR(200) NOT NULL,
  type VARCHAR(20) NOT NULL,
  script VARCHAR(1000) NOT NULL,
  checksum INT,
  installed_by VARCHAR(100) NOT NULL,
  installed_on TIMESTAMP DEFAULT now() NOT NULL,
  execution_time INT NOT NULL,
  success BOOLEAN NOT NULL
);
CREATE TABLE IF NOT EXISTS users
(
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) NOT NULL,
  username VARCHAR(512) NOT NULL,
  password VARCHAR(512) NOT NULL,
  enabled BOOLEAN,
  hash_code VARCHAR(512),
  confirmation_hash_code VARCHAR(512),
  confirmed BOOLEAN,
  preferred_language VARCHAR(512),
  current_organization_id INT,
  most_recently_used_oauth_service VARCHAR(512),
  use_oauth BOOLEAN,
  github_access_token VARCHAR(512),
  linkedin_access_token VARCHAR(512),
  twitter_access_token VARCHAR(512),
  xing_access_token VARCHAR(512),
  temporary_user BOOLEAN DEFAULT false,
  custom_signature VARCHAR(512),
  profile_image_path VARCHAR(512),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  synchronized_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  connections_last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
