ALTER TABLE users
  ADD COLUMN updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users
  ADD COLUMN synchronized_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE contacts
  ADD COLUMN updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE organizations
  ADD COLUMN updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;